server:
  port: 7002
eureka:
  instance:
    hostname: ${EUREKA-DOMAIN:eureka02}
  client:
    register-with-eureka: false  #表示不向注册中心注册自己
    fetch-registry: false
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka03:7003/eureka/
